# Generated by Django 5.1.1 on 2024-09-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_post',
            new_name='Films_post',
        ),
        migrations.AlterModelOptions(
            name='films_post',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
